theme: jekyll-theme-midnight
https://github.com/T-Dev-CCM/WMAG-Showcase/blob/gh-pages/images/image9.jpeg?raw=true
description: "Character Preview"
gitorg: "https://github.com/jm1021/leuck_reunion"
google_analytics:
